#!/bin/sh

# check needed vars
if [[ -z $OPENSHIFT_REPO_DIR ]]; then
	echo "Error: OPENSHIFT_REPO_DIR not defined"
	return 1
fi;

if [[ -z $OPENSHIFT_DATA_DIR ]]; then
	echo "Error: OPENSHIFT_DATA_DIR not defined"
	return 1
fi;

if [[ -z $OPENSHIFT_TMP_DIR ]]; then
	echo "Error: OPENSHIFT_TMP_DIR not defined"
	return 1
fi;

if [[ -z $OPENSHIFT_LOG_DIR ]]; then
	echo "Error: OPENSHIFT_LOG_DIR not defined"
	return 1
fi;

ln -s $OPENSHIFT_REPO_DIR/vhost $OPENSHIFT_REPO_DIR/php
#env > $OPENSHIFT_LOG_DIR/build.env

