<?php
$login="ierp_inm";
$passwd="password";
$cfgServer="dbserver.h.tite.as";
$port="3306";
$cfgDbase="_main";
$dbase="betatest_gestion_inmersa";
$APP_NAME="IGestion";
$mod_path="modulos/";
$BACKOFFICE=TRUE;
$DEBUG="ON";
?>
